name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version-file: .python-version

    - uses: astral-sh/setup-uv@v6

    - run: uvx ruff check

    - run: uvx ruff format --check

    - run: uvx run pytest
